config/routes.rb
Rails.application.routes.draw do
  

  apipie
  namespace :api do
      namespace :v1 do
        resources :products
        resources :categories
      end
  end
  resources :sizes
  resources :tax_rates
  resources :brands
 
  scope "suppliers/:supplier_id" do
    resources :registration_steps
  end

  resources :suppliers do
    resources :contacts
    resources :addresses
    resources :finances
  end

  resources :purchase_orders
  
  
  get 'dashboard' => 'dashboard#index'

  resources :products do
    resources :variants
  end

  resources :categories do
    resources :subcategories
  end

   root 'welcome#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :supplier, inverse_of: :contact
end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories, dependent: :destroy
	validates :name, :description, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :supplier, inverse_of: :contact
end

app/models/finance.rb
class Finance < ActiveRecord::Base
  belongs_to :supplier, inverse_of: :finance
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :purchase_order
end

app/models/procurement.rb
class Procurement < ActiveRecord::Base
  belongs_to :purchase_order
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  # Add dependencies for products
  #require_dependency provides a way to load a file using the current 
  #loading mechanism, and keeping track of constants defined in that file
  # as if they were autoloaded to have them reloaded as needed.
  
  require_dependency 'product/variants'

  belongs_to :subcategory
  serialize :properties, Hash
  has_many :fields, class_name: "ProductField"
  accepts_nested_attributes_for :fields, allow_destroy: true
  belongs_to :supplier
  belongs_to :brand
  belongs_to :tax_rate
  belongs_to :size
  
  def is_a_variant?
      self.parent_id.nil?
  end

end

app/models/product_field.rb
class ProductField < ActiveRecord::Base
  belongs_to :subcategory
  #attr_accessible :field_type, :name, :required
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  belongs_to :supplier
end

app/models/size.rb
class Size < ActiveRecord::Base

  def description
    "#{name}   (#{volume} #{unit})"
  end
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  has_many :fields, class_name: "ProductField"
  accepts_nested_attributes_for :fields, allow_destroy: true 
  validates :name, :description, presence: true
  has_many :products, dependent: :destroy

  def has_products?
    !self.products.empty?
  end
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_one :contact, inverse_of: :supplier
  has_many :address, inverse_of: :supplier
  has_one :finance, inverse_of: :supplier
  has_many :products, inverse_of: :supplier
  has_many :purchase_orders
end

app/models/tax_rate.rb
class TaxRate < ActiveRecord::Base
  has_one :product

  def tax_description
    "#{code} - #{name} (#{rate}%)"
  end
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: [:show, :edit, :update, :destroy]

  def edit
  end

  def update
    if @finance.update(finance_params)
      redirect_to [@supplier, @contact] , notice: "Financial information is updated successfully"
    end
  end

  def destroy

    @finance.destroy if !@finance.nil?
    redirect_to supplier_url(@supplier), notice: "Financial information deleted successfully"
  end

  private

  def set_finance
    @supplier = Supplier.find(params[:supplier_id])
    @finance = @supplier.finance
  end 

  #Repeted code, supplier controller
  def finance_params
      params.require(:finance).permit(:price_list, :currency, :tax_code, :email, :registration_number, :payment_method, :credit_limit, :credit_lead_time , :bank_name, :account_number, :IFSC_code)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/finances/_form.html.haml
= simple_form_for [@supplier, @finance], :html => { :class => 'form-horizontal' } do |f|
  = f.input :price_list
  = error_span(@finance[:price_list])
  = f.input :currency
  = error_span(@finance[:currency])
  = f.input :tax_code
  = error_span(@finance[:tax_code])
  = f.input :email
  = error_span(@finance[:email])
  = f.input :registration_number
  = error_span(@finance[:registration_number])
  = f.input :payment_method
  = error_span(@finance[:payment_method])
  = f.input :credit_limit
  = error_span(@finance[:credit_limit])
  = f.input :credit_lead_time
  = error_span(@finance[:credit_lead_time])
  = f.input :bank_name
  = error_span(@finance[:bank_name])
  = f.input :account_number
  = error_span(@finance[:account_number])
  = f.input :IFSC_code
  = error_span(@finance[:IFSC_code])
  = f.input :supplier_id
  = error_span(@finance[:supplier_id])
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), supplier_path, :class => 'btn btn-default'

app/views/finances/_show.html.haml
- model_class = Finance
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:price_list) + ':'
  %br
  = @finance.price_list
%p
  %strong= model_class.human_attribute_name(:currency) + ':'
  %br
  = @finance.currency
%p
  %strong= model_class.human_attribute_name(:tax_code) + ':'
  %br
  = @finance.tax_code
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @finance.email
%p
  %strong= model_class.human_attribute_name(:registration_number) + ':'
  %br
  = @finance.registration_number
%p
  %strong= model_class.human_attribute_name(:payment_method) + ':'
  %br
  = @finance.payment_method
%p
  %strong= model_class.human_attribute_name(:credit_limit) + ':'
  %br
  = @finance.credit_limit
%p
  %strong= model_class.human_attribute_name(:credit_lead_time) + ':'
  %br
  = @finance.credit_lead_time
%p
  %strong= model_class.human_attribute_name(:bank_name) + ':'
  %br
  = @finance.bank_name
%p
  %strong= model_class.human_attribute_name(:account_number) + ':'
  %br
  = @finance.account_number
%p
  %strong= model_class.human_attribute_name(:IFSC_code) + ':'
  %br
  = @finance.IFSC_code
%p
  %strong= model_class.human_attribute_name(:supplier_id) + ':'
  %br
  = @finance.supplier_id


= link_to t('.back', :default => t("helpers.links.back")), supplier_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_supplier_finance_path(@supplier, @finance), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), supplier_finance_path(@supplier, @finance), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/finances/edit.html.haml
- model_class = Finance
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/finances/index.html.haml
- model_class = Finance
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:price_list)
      %th= model_class.human_attribute_name(:currency)
      %th= model_class.human_attribute_name(:tax_code)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:registration_number)
      %th= model_class.human_attribute_name(:payment_method)
      %th= model_class.human_attribute_name(:credit_limit)
      %th= model_class.human_attribute_name(:credit_lead_time)
      %th= model_class.human_attribute_name(:bank_name)
      %th= model_class.human_attribute_name(:account_number)
      %th= model_class.human_attribute_name(:IFSC_code)
      %th= model_class.human_attribute_name(:supplier_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @finances.each do |finance|
      %tr
        %td= link_to finance.id, finance_path(finance)
        %td= finance.price_list
        %td= finance.currency
        %td= finance.tax_code
        %td= finance.email
        %td= finance.registration_number
        %td= finance.payment_method
        %td= finance.credit_limit
        %td= finance.credit_lead_time
        %td= finance.bank_name
        %td= finance.account_number
        %td= finance.IFSC_code
        %td= finance.supplier_id
        %td=l finance.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_finance_path(finance), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), finance_path(finance), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_finance_path, :class => 'btn btn-primary'

app/views/finances/new.html.haml
- model_class = Finance
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/finances/show.html.haml
= render 'show'