config/routes.rb
Rails.application.routes.draw do
  

  apipie
  namespace :api do
      namespace :v1 do
        resources :products
        resources :categories
      end
  end
  resources :sizes
  resources :tax_rates
  resources :brands
 
  scope "suppliers/:supplier_id" do
    resources :registration_steps
  end

  resources :suppliers do
    resources :contacts
    resources :addresses
    resources :finances
  end

  resources :purchase_orders
  
  
  get 'dashboard' => 'dashboard#index'

  resources :products do
    resources :variants
  end

  resources :categories do
    resources :subcategories
  end

   root 'welcome#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :supplier, inverse_of: :contact
end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories, dependent: :destroy
	validates :name, :description, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :supplier, inverse_of: :contact
end

app/models/finance.rb
class Finance < ActiveRecord::Base
  belongs_to :supplier, inverse_of: :finance
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :purchase_order
end

app/models/procurement.rb
class Procurement < ActiveRecord::Base
  belongs_to :purchase_order
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  # Add dependencies for products
  #require_dependency provides a way to load a file using the current 
  #loading mechanism, and keeping track of constants defined in that file
  # as if they were autoloaded to have them reloaded as needed.
  
  require_dependency 'product/variants'

  belongs_to :subcategory
  serialize :properties, Hash
  has_many :fields, class_name: "ProductField"
  accepts_nested_attributes_for :fields, allow_destroy: true
  belongs_to :supplier
  belongs_to :brand
  belongs_to :tax_rate
  belongs_to :size
  
  def is_a_variant?
      self.parent_id.nil?
  end

end

app/models/product_field.rb
class ProductField < ActiveRecord::Base
  belongs_to :subcategory
  #attr_accessible :field_type, :name, :required
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  belongs_to :supplier
end

app/models/size.rb
class Size < ActiveRecord::Base

  def description
    "#{name}   (#{volume} #{unit})"
  end
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  has_many :fields, class_name: "ProductField"
  accepts_nested_attributes_for :fields, allow_destroy: true 
  validates :name, :description, presence: true
  has_many :products, dependent: :destroy

  def has_products?
    !self.products.empty?
  end
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_one :contact, inverse_of: :supplier
  has_many :address, inverse_of: :supplier
  has_one :finance, inverse_of: :supplier
  has_many :products, inverse_of: :supplier
  has_many :purchase_orders
end

app/models/tax_rate.rb
class TaxRate < ActiveRecord::Base
  has_one :product

  def tax_description
    "#{code} - #{name} (#{rate}%)"
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
	def create
		@category = Category.find(params[:category_id])
    p subcategory_params
		@subcategory = @category.subcategories.create(subcategory_params)
		if @subcategory.save
			redirect_to category_path(@category), :flash => { :notice => "Successfully created  subcategory " }
		else
			redirect_to category_path(@category), :flash => { :notice => "Something went wrong" }
		end
	end

  def edit
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.find(params[:id])
    if @subcategory.update(subcategory_params)
      redirect_to category_path(@category), :flash => {:notice => "Successfully updated"}
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.find(params[:id])
    @products = Product.where(subcategory_id: params[:id] )
  end

	private
	def subcategory_params
		params.require(:subcategory).permit(:name, :description, fields_attributes: [:id, :field_type, :name])	
	end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/subcategories/_field_fields.html.haml
= f.select :field_type, %w[text_field check_box shirt_sizes numeric mg], :class => "caret"
= f.text_field :name, placeholder: "Tyme custom field name here", :class => "form-control"
= f.hidden_field :_destroy
= link_to "remove", '#', class: "remove_fields"
%br 

app/views/subcategories/_form.html.haml
= simple_form_for ([@category, @subcategory]), :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = error_span(@category[:name])
  = f.input :description
  = error_span(@category[:description])
  - f.fields_for :field do |builder|
    = render 'subcategories/field_fields', f: builder 
  %br
  = link_to_add_fields "Add Field", f, :fields, 'add_fields btn btn-success pull-right btn-lg'
  %br
  %br
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), categories_path, :class => 'btn btn-default'

  

app/views/subcategories/_product_list.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:skuid)
      %th= model_class.human_attribute_name(:brand)
      %th= model_class.human_attribute_name(:category)
      - @products.last.properties.keys.each do |prop|
        %th= model_class.human_attribute_name(prop)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @products.each do |product|
      %tr
        %td= link_to product.id, product_path(product)
        %td= product.name
        %td= product.skuid
        %td= product.brand
        %td 
          = link_to t(product.subcategory.name, :default => product.subcategory.name), category_subcategory_path(product.subcategory.category, product.subcategory), :class => 'btn btn-info btn-xs'
        - @products.last.properties.values.each do |val|
          %td= val
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(product), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= form_tag new_product_path, method: :get 
= select_tag 'subcategory_id', options_from_collection_for_select(Subcategory.all, :id, :name, 1)
= submit_tag "new", name: nil, :class => 'btn btn-primary'

app/views/subcategories/edit.html.haml
- model_class = Subcategory
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/subcategories/index.html.haml
- model_class = Subcategory
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:category_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @subcategories.each do |subcategory|
      %tr
        %td= link_to subcategory.id, subcategory_path(subcategory)
        %td= subcategory.name
        %td= subcategory.description
        %td= subcategory.category_id
        %td=l subcategory.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_subcategory_path(subcategory), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), subcategory_path(subcategory), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_subcategory_path, :class => 'btn btn-primary'

app/views/subcategories/new.html.haml
- model_class = Subcategory
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/subcategories/show.html.haml
- model_class = Subcategory

.container-fluid
  .row.bg-primary
    .col-sm-9
      .page-header
        %h1=t '.title', :default => @subcategory.name.titleize
  .row.bg-info.text-center
    .col-sm-9
      %p
      %h3
        = @subcategory.description
 
  =render 'product_list'

  = link_to t('.back', :default => t("helpers.links.back")), category_path(@category), :class => 'btn btn-default'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_category_subcategory_path(@category, @subcategory), :class => 'btn btn-default'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), category_subcategory_path(@category, @subcategory), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'