config/routes.rb
Rails.application.routes.draw do
  

  apipie
  namespace :api do
      namespace :v1 do
        resources :products
        resources :categories
      end
  end
  resources :sizes
  resources :tax_rates
  resources :brands
 
  scope "suppliers/:supplier_id" do
    resources :registration_steps
  end

  resources :suppliers do
    resources :contacts
    resources :addresses
    resources :finances
  end

  resources :purchase_orders
  
  
  get 'dashboard' => 'dashboard#index'

  resources :products do
    resources :variants
  end

  resources :categories do
    resources :subcategories
  end

   root 'welcome#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :supplier, inverse_of: :contact
end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories, dependent: :destroy
	validates :name, :description, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :supplier, inverse_of: :contact
end

app/models/finance.rb
class Finance < ActiveRecord::Base
  belongs_to :supplier, inverse_of: :finance
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :purchase_order
end

app/models/procurement.rb
class Procurement < ActiveRecord::Base
  belongs_to :purchase_order
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  # Add dependencies for products
  #require_dependency provides a way to load a file using the current 
  #loading mechanism, and keeping track of constants defined in that file
  # as if they were autoloaded to have them reloaded as needed.
  
  require_dependency 'product/variants'

  belongs_to :subcategory
  serialize :properties, Hash
  has_many :fields, class_name: "ProductField"
  accepts_nested_attributes_for :fields, allow_destroy: true
  belongs_to :supplier
  belongs_to :brand
  belongs_to :tax_rate
  belongs_to :size
  
  def is_a_variant?
      self.parent_id.nil?
  end

end

app/models/product_field.rb
class ProductField < ActiveRecord::Base
  belongs_to :subcategory
  #attr_accessible :field_type, :name, :required
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  belongs_to :supplier
end

app/models/size.rb
class Size < ActiveRecord::Base

  def description
    "#{name}   (#{volume} #{unit})"
  end
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  has_many :fields, class_name: "ProductField"
  accepts_nested_attributes_for :fields, allow_destroy: true 
  validates :name, :description, presence: true
  has_many :products, dependent: :destroy

  def has_products?
    !self.products.empty?
  end
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_one :contact, inverse_of: :supplier
  has_many :address, inverse_of: :supplier
  has_one :finance, inverse_of: :supplier
  has_many :products, inverse_of: :supplier
  has_many :purchase_orders
end

app/models/tax_rate.rb
class TaxRate < ActiveRecord::Base
  has_one :product

  def tax_description
    "#{code} - #{name} (#{rate}%)"
  end
end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < Api::V1::BaseController

  api :GET, "/api/v1/categories", "Get all Categories"
  example " [
  {
    'id': 1,
    'name': 'Ice cream',
    'description': 'A sample description of SubCategory'
  },
  {
    'id': 2,
    'name': 'Cake',
    'description': 'another sub category'
  },
  {
    'id': 3,
    'name': 'Just a test',
    'description': 'a sampl'
  }
  ] "
  formats ['json']

  def index
    @subcategories = Subcategory.all
  end
  


  
  api :GET, '/api/v1/categories/:id', "Get Products by Category"
  description "Get all Product(s)/ Variant(s) of a particular Category"
  formats ['json']
  example "{
  'id': 2,
  'name': 'Cake',
  'description': 'another sub category',
  'products': [
    {
      'product': {
        'id': 6,
        'name': 'Chokoturt',
        'skuid': 'CKSR',
        'short_description': 'something',
        'active': true,
        'quantity': 5,
        'price': '200.0',
        'created_at': '2016-01-16 20:08:37 UTC',
        'updated_at': '2016-01-16 20:08:37 UTC'
      }
    },
    {
      'product': {
        'id': 7,
        'name': 'Mamba',
        'skuid': 'MBM',
        'short_description': 'something',
        'active': true,
        'quantity': 56,
        'price': '456.0',
        'created_at': '2016-01-16 20:14:02 UTC',
        'updated_at': '2016-01-16 20:14:02 UTC'
        }
      }
    ]
  }"
  def show
    @subcategory = Subcategory.find(params[:id])
    products = @subcategory.products.all
    @variants = []
    
    products.each do |product|
      if product.has_variants?
        product.variants.all.each { |variant| @variants << variant }
      else product.has_not_variants?
        @variants << product
      end
    end
    @variants
  end


  

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to :categories, :flash => { :notice => "Success" }	
		else
			render 'new'
		end
	end

	def index
		@categories = Category.all
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])

		if @category.update(category_params)
			redirect_to categories_path
		else
			render 'edit'
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy

		redirect_to categories_path
	end

	def show
		@category = Category.find(params[:id])
		@subcategories = @category.subcategories.all
		@subcategory = @category.subcategories.new
  end

	private

	def category_params
		params.require(:category).permit(:name, :description)	
	end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.haml
= simple_form_for @category, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = error_span(@category[:name])
  = f.input :description
  = error_span(@category[:description])
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), categories_path, :class => 'btn btn-default'

app/views/categories/edit.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/categories/index.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @categories.each do |category|
      %tr
        %td= link_to category.id, category_path(category)
        %td= category.name
        %td= category.description
        %td=l category.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(category), :class => 'btn btn-default btn-xs'
          = link_to t('.add', :default => t("helpers.links.Subcategory")), category_path(category), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(category), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_category_path, :class => 'btn btn-primary'

app/views/categories/new.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/categories/show.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @category.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @category.description

= link_to t('.back', :default => t("helpers.links.back")), categories_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(@category), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(@category), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

- if !@subcategories.nil?
  %h1=t '.title.', :default => "Subcategories"
  %table.table.table-striped
    %thead
      %tr
        %th= model_class.human_attribute_name(:id)
        %th= model_class.human_attribute_name(:name)
        %th= model_class.human_attribute_name(:description)
        %th= model_class.human_attribute_name(:category_id)
        %th= model_class.human_attribute_name(:created_at)
        %th=t '.actions', :default => t("helpers.actions")
    %tbody
      - @subcategories.each do |subcategory|
        %tr
          %td= link_to subcategory.id, category_path(@category)
          %td= subcategory.name
          %td= subcategory.description
          %td= subcategory.category_id
          %td=l subcategory.created_at
          %td
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_category_subcategory_path(@category, subcategory), :class => 'btn btn-default btn-xs'
            = link_to t('.show', :default => t("helpers.links.show")), category_subcategory_path(@category, subcategory), :class => 'btn btn-default btn-xs'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), category_subcategory_path(@category, subcategory), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

  / = link_to t('.new', :default => t("helpers.links.new")), new_subcategory_path, :class => 'btn btn-primary'

- else
  %h3= "No Subcategory exists"

%p
  %br
    %h2 Add a subcategory
= render :partial => "subcategories/form"