config/routes.rb
Rails.application.routes.draw do
  

  apipie
  namespace :api do
      namespace :v1 do
        resources :products
        resources :categories
      end
  end
  resources :sizes
  resources :tax_rates
  resources :brands
 
  scope "suppliers/:supplier_id" do
    resources :registration_steps
  end

  resources :suppliers do
    resources :contacts
    resources :addresses
    resources :finances
  end

  resources :purchase_orders
  
  
  get 'dashboard' => 'dashboard#index'

  resources :products do
    resources :variants
  end

  resources :categories do
    resources :subcategories
  end

   root 'welcome#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  # Add dependencies for products
  #require_dependency provides a way to load a file using the current 
  #loading mechanism, and keeping track of constants defined in that file
  # as if they were autoloaded to have them reloaded as needed.
  
  require_dependency 'product/variants'

  belongs_to :subcategory
  serialize :properties, Hash
  has_many :fields, class_name: "ProductField"
  accepts_nested_attributes_for :fields, allow_destroy: true
  belongs_to :supplier
  belongs_to :brand
  belongs_to :tax_rate
  belongs_to :size
  
  def is_a_variant?
      self.parent_id.nil?
  end

end

app/models/product/variants.rb
class Product < ActiveRecord::Base
  has_many :variants, :class_name => "Product", :foreign_key => "parent_id", dependent: :destroy
  belongs_to :parent, :class_name => "Product"

  #If Product has variants then update the parent product pricing info
  # also update variant with parent product field
  
  before_save do 
    if self.parent
      self.tax_rate = self.parent.tax_rate
      self.supplier_id = self.parent.supplier_id
      self.brand_id = self.parent.brand_id
      self.description = self.parent.description
      self.short_description = self.parent.short_description
    end
  end
      
      
  after_save do
    if self.parent
      self.parent.price = 0
      self.parent.cost_price = 0
      self.parent.quantity = 0
      self.parent.size_id  = nil
     
      self.parent.save if self.parent.changed?
    end
  end

  def has_variants?
      !variants.empty?
  end

  
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::V1::BaseController
  
  api :GET, 'api/v1/products', "Get All Products"
  description "Get all Product(s)/ Variant(s) present in the inventory"
  formats ['json']
  example "[
    {
      'id': 2,
      'name': 'Choko Lava',
      'skuid': 'CHKL',
      'short_description': 'a short description for our product',
      'active': true,
      'quantity': 0,
      'price': '0.0',
      'created_at': '2016-01-16 16:51:41 UTC',
      'updated_at': '2016-01-16 18:53:31 UTC'
    },
    {
      'id': 5,
      'name': 'Black forest',
      'skuid': 'asxd',
      'short_description': 'a short description for our product',
      'active': true,
      'quantity': 14,
      'price': '212.0',
      'created_at': '2016-01-16 18:55:31 UTC',
      'updated_at': '2016-01-16 18:55:31 UTC'
    },
    {
      'id': 7,
      'name': 'Mamba',
      'skuid': 'MBM',
      'short_description': 'something',
      'active': true,
      'quantity': 56,
      'price': '456.0',
      'created_at': '2016-01-16 20:14:02 UTC',
      'updated_at': '2016-01-16 20:14:02 UTC'
    }
  ]"
  def index
    products = Product.all
    @variants = []
    
    products.each do |product|
      if product.has_variants?
        product.variants.all.each { |variant| @variants << variant }
      elsif product.is_a_variant?
        @variants << product
      end
    end
    @variants
  end

  api :GET, 'api/v1/products/id', "Get details of a Product"
  description "Get details of a Product"
  formats ['json']
    example "{
    'id': 2,
    'name': 'Kulfi Malai',
    'skuid': 'klfm',
    'short_description': 'for mobile',
    'quantity': 7,
    'price': '78.0',
    'parent_id': null,
    'subcategory_id': 1
  }"
  def show
    #TO ugly clean up 
    product = Product.find(params[:id])
    if !product.is_a_variant?
      @variant = product
    elsif !product.has_variants?
      @variant = product
    end
    @variant
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @cat = Category.all
    @categories = Category.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    #TODO Refactor, Nasty code
    @product = Product.new(subcategory_id: params[:subcategory_id])
    @subcategory_names = Subcategory.all.map{|sub| [sub.name, sub.id] }
    @supplier_names = Supplier.all.map{|sup| [sup.company, sup.id]}
    @brand_names = Brand.all.map{|br| [br.name, br.id]}
    @default_brand = @brand_names.first
    @default_subcategory = @subcategory_names.first
    @default_supplier  = @subcategory_names.first
    @tax_rates = TaxRate.all.map{|tr| [tr.tax_description, tr.id]}
    @default_tax_rate = @tax_rates.first

    @sizes = Size.all.map{|s| [s.description, s.id]}
    @default_size = @sizes.first
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @subcategory_names = Subcategory.all.map{|sub| [sub.name, sub.id] }
    @supplier_names = Supplier.all.map{|sup| [sup.company, sup.id]}
    @brand_names = Brand.all.map{|br| [br.name, br.id]}
    @default_brand =  [@product.brand.name, @product.brand.id ]
    @default_subcategory = [@product.subcategory.name, @product.subcategory.id]
    @default_supplier = [@product.supplier.company, @product.supplier.id]
    @tax_rates = TaxRate.all.map{|tr| [tr.tax_description, tr.id]}
    @default_tax_rate = [@product.tax_rate.tax_description, @product.tax_rate.id]
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :skuid, :brand_id, :tax_rate_id, 
                                      :subcategory_id, :supplier_id, 
                                      :permalink, :description, :short_description, 
                                      :price, :cost_price, :size_id, :quantity, 
                                       properties: params[:product][:properties].try(:keys))
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= simple_form_for @product, :html => { :class => 'form-horizontal' } do |f|
  = f.hidden_field :subcategory_id
  = f.input :name
  = error_span(@product[:name])
  = f.input :supplier_id, collection: @supplier_names, :selected => @default_supplier 
  = f.input :subcategory_id, :label => "Product Category", :collection => @subcategory_names, :selected => @default_subcategory
  = f.input :brand_id, :label => "Brand", :collection => @brand_names, :selected => @default_brand
  = error_span(@product[:brand])
  = f.input :skuid
  = error_span(@product[:skuid])
  = f.input :permalink
  = error_span(@product[:permalink])
  = f.input :description
  = error_span(@product[:description])
  = f.input :short_description
  = error_span(@product[:short_description])

  = f.input :price
  = error_span(@product[:price])
  = f.input :cost_price
  = error_span(@product[:cost_price])
  = f.input :tax_rate_id, :collection => @tax_rates, :selected => @default_tax_rate

  = f.input :size_id, :collection => @sizes, :selected => @default_size
    
  = f.input :quantity
  = error_span(@product[:quantity])
   
  = f.fields_for :properties, OpenStruct.new(@product.properties) do |builder|
    - if !@product.subcategory.nil?
      - @product.subcategory.fields.each do |field|
        = render "products/fields/#{field.field_type}", field: field, f:builder 
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), products_path, :class => 'btn btn-default'

app/views/products/_table.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
  = form_tag new_product_path, method: :get 
  = submit_tag "new", name: nil, :class => 'btn btn-primary'

%table.table.table-bordered
  %thead
    %tr
      %th{:width => '10%'}= model_class.human_attribute_name(:sku)
      %th{:width => '35%'}= model_class.human_attribute_name(:name)
      %th{:width => '25%'}= t('products.price_variants')
      %th{:width => '15%'}= t('products.stock')
      - if !products.empty?
        - products.last.properties.keys.each do |prop|
          %th= model_class.human_attribute_name(prop)
      %th{:width => '15%'}=t '.actions', :default => t("helpers.actions")
  %tbody
    - if products.empty?
      %tr.empty
      %td{:colspan => 5}= t('products.no_products')
    - else
      - categories.each do |category|
        - category.subcategories.each do |subcategory|
          %tr
          -if subcategory.has_products?
            %th{:colspan => 5}= link_to t(subcategory.name, :default => subcategory.name), category_subcategory_path(subcategory.category, subcategory), :class => 'btn btn-info btn-xs'
            - subcategory.products.each do |product|
              %tr
                %td= link_to product.skuid, product_path(product)
                %td= product.name
                - if product.has_variants?
                  %td.multistage{:colspan => 2}
                    %table.table.table-bordered#inner-table
                      - product.variants.each do |variant|
                        %tr
                          %td{:width => '50%'}= link_to variant.name, edit_product_variant_path(product, variant)
                          %td{:width => '25%'}= number_to_currency variant.price
                          %td{:width => '25%'}= variant.quantity
                - else
                  %td= number_to_currency product.price
                  %td= product.quantity
                - products.last.properties.values.each do |val|
                  %td= val
                %td
                  = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(product), :class => 'btn btn-default btn-xs'
                  = link_to t('variants.add_variants'), [:new, product, :variant], :class => 'btn btn-primary btn-xs'
                  = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/products/edit.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
  = link_to t('Variants') , [@product, :variants], :class => 'button'
= render :partial => "form"

app/views/products/index.html.haml
= render "table", :products => @products, :categories => @categories 

app/views/products/new.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/products/show.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @product.name
%p
  %strong= model_class.human_attribute_name(:skuid) + ':'
  %br
  = @product.skuid

%p
  %strong= model_class.human_attribute_name(:product_type) + ':'
  %br
  = @product.subcategory.name
%p
  %strong= model_class.human_attribute_name(:supplier) + ':'
  %br
  = @product.supplier.company
%p
  %strong= model_class.human_attribute_name(:brand) + ':'
  %br
  = @product.brand.name

= link_to t('.back', :default => t("helpers.links.back")), products_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(@product), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(@product), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'